{% set name = "restructuredtext_lint" %}
{% set version = "1.3.0" %}
{% set sha256 = "97b3da356d5b3a8514d8f1f9098febd8b41463bed6a1d9f126cf0a048b6fd908" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{name}}-{{version}}.tar.gz
  url: https://pypi.io/packages/source/{{name[0]}}/{{name}}/{{name}}-{{version}}.tar.gz
  sha256: {{sha256}}

build:
    noarch: python
    script: python setup.py install --single-version-externally-managed --record record.txt
    number: 0
    entry_points:
        - rst-lint = restructuredtext_lint.cli:main
        - restructuredtext-lint = restructuredtext_lint.cli:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - docutils >=0.11,<1.0

test:
  imports:
    - restructuredtext_lint
  commands:
    - rst-lint -h
    - restructuredtext-lint -h

about:
  home: https://github.com/twolfson/restructuredtext-lint
  license: Unlicense
  license_file: UNLICENSE
  license_family: Public-Domain
  summary: 'Lint reStructuredText files'
  dev_url: https://github.com/twolfson/restructuredtext-lint

extra:
  recipe-maintainers:
    - dopplershift
