travis:
  secure:
    BINSTAR_TOKEN: fYGSuZevjCQW9Jzxim+If2Csm7ionQrb5y/ZwH6he5iYO/zEoJhH77frCTMtdEPkcmBtryj4KjL4Nm735uf3hXwvrVDfo0KkT5mcobmiyU3e9ooksUeMKj4O0LNGT+FbGY7JVy6rUwHuLniEBsMs09S6CPlp9W6/dFAACqdC2qiJe9mXFMlhySHM/8I9dmxGFWl6DmZByGv2FcQr5ILQF2itZlHGT3BH5/YMn79/3I6pc7EL3CCmDu9ZDNFJ9R4jc2iDoEHEVwdH8JQVKh5hls5rvn7Gdozt58Odq6HZ7mO8aXvHvJF16HaSvRhE0bannOc8tgdq3GFp0qbNSRMIynXUzd4EnUy6zYPis+sqSjtuaQTMXbieR8siw9F0MpqERuTF0dyjBlXo9TqYtuRf3ikzaTb/X4VLeR8CnGk9LQPs8xrUKJRQyYDj+RQBArNdbTuNfg2SK/qfmDISP8pRz2wlXpa9Oa9sk21rZMikpgQi4RxjeWPohKubJ/xX/xKdQcsS1rlHcPeJ7bmS3Y8vw1W42tmcjryCBZpw0YvWnJYlPv2rww4jNTN47E72kQ1B98RqqyUxqBE9X9eoWoE2xKavuq7rhW/X1mnkN9YWizo3zLpeWJ8QU6RlIJrvekcdBHL9++2ssMtDSDl84gJ5jOcBSGOZsfLM5DueKbVo2U0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
