travis:
  secure:
    BINSTAR_TOKEN: M2VxH8Lyrlgs4/QIxXkr8twLQ0kOaz2oWkal3fzNRxB7b+QF1bdPHjFSV+1vTYsrbiSGmclsyuojDpp2BJEtE8AGsvSaPsOiN25HIDVwulKKL5QEUp0AGoGA2tbjXy21RDltQX5p9Tacjz/w3KqLGvUUqoKpeBUN4ZbSIikQ0OqnriXSqVo21Bskl9lqjKc1i87ZKAjznibgO9r82T7HzBzjzXadmv4HpwDbtAO7uvDYz/PWhPMAP0HAGou5NYcKPTPA4DwcpHR5qdq76zBvNsvllQ0D3ex8gZ6GmEYVwHWL8nk9RG/qq6RjbA7nm7ycn7PJf8gcMBp8VURF0N85ORvQmd+EZv+nwSFmqx/TKBJkK2BeWUs6t2tq5y1NJvc2fywxKizZMnGY8YgWx4M8G1i65RLWz6UtwxK9fZuaMGl8EOV4A7/02evLV8XCKAYx1H1OXtQfxMD1EAhVk9Ho/+LKyF4ASnwmiTjdiiNiIbvqvfiE3wXr7p2HyW/BKb7RDfhZWIIIlLfHNWd9t4CQOn54YQwCSVRbYwdjQT8dL77S17go4V7yFoLuZdI6QqA+DgrB87z4E6j894FczD0Xr/es605w/3pQ4d/+2gGnbXfajiu3JVH+j07e7LikCZrGFau85rZtalZMUKDDNWkMINCQtJV4g6kp8w+ct4wwzsc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
